name: molecule-test

on:
  workflow_call:
    inputs:
      distro_image:
        required: true
        type: string
      distro_tag:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      python_version:
        required: false
        type: string
        default: "3.12"

permissions:
  contents: read # This is required for actions/checkout
  packages: write # This is required to push images to Github packages
  id-token: write # This is required for requesting the JWT

jobs:
  lint:
    name: run_lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5
        with:
          path: "${{ inputs.working_directory }}"

      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: "${{ inputs.python_version }}"

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3

      - name: ansible-lint
        uses: ansible/ansible-lint@main
        with:
          args: "-c .ansible-lint"
          setup_python: "false"


  molecule:
    needs:
      - run_lint
    name: run_molecule
    runs-on: ubuntu-latest

    env:
      ANSIBLE_CALLBACK_WHITELIST: profile_tasks
      ANSIBLE_STDOUT_CALLBACK: yaml
      ANSIBLE_VERBOSITY: 1
      ANSIBLE_LOAD_CALLBACK_PLUGINS: true

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v5
        with:
          path: "${{ inputs.working_directory }}"

      - name: Set up Python 3.
        uses: actions/setup-python@v6
        with:
          python-version: "${{ inputs.python_version }}"

      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
#          molecule_options: --debug --base-config molecule/_shared/base.yml
          molecule_command: test
#          molecule_args: --scenario-name ${{ matrix.scenario }}
        env:
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ inputs.distro_image }}
          MOLECULE_DISTRO_TAG: ${{ inputs.distro_tag }}

#      - name: Install test dependencies.
#        run: |
#          pip3 install ansible-core==2.17.10 molecule==25.3.1 molecule-plugins[docker] docker

#      - name: Run Molecule tests.
#        run: molecule test
#        env:
#          PY_COLORS: "1"
#          ANSIBLE_FORCE_COLOR: "1"
#          MOLECULE_DISTRO: ${{ inputs.distro_image }}
#          MOLECULE_DISTRO_TAG: ${{ inputs.distro_tag }}


